'use client'

import { useState } from 'react'
import { ChevronDown } from 'lucide-react'

// 🆕 SEO: FAQ Schema helps Google present answering rich snippets on the search engine results page (SERP)
export function FAQSection() {
    const faqs = [
        {
            question: "What is ContentJet?",
            answer: "ContentJet is an AI-powered content generation platform that helps you create blog posts, social media content, emails, and advertisements in seconds using advanced artificial intelligence."
        },
        {
            question: "How does the AI content generator work?",
            answer: "ContentJet uses state-of-the-art AI language models to understand your input and generate high-quality, original content based on your requirements. Simply provide a topic or prompt, choose your content type, and our AI creates professional content in seconds."
        },
        {
            question: "Is the AI-generated content unique?",
            answer: "Yes, all content generated by ContentJet is 100% unique and original. Our AI creates new content from scratch based on your inputs, ensuring plagiarism-free results every time."
        },
        {
            question: "What types of content can I create?",
            answer: "You can create blog posts, social media posts, email campaigns, product descriptions, ad copy, SEO content, and more. ContentJet supports multiple content formats and tones."
        }
    ]

    const faqStructuredData = {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": faqs.map(faq => ({
            "@type": "Question",
            "name": faq.question,
            "acceptedAnswer": {
                "@type": "Answer",
                "text": faq.answer
            }
        }))
    }

    const [openIndex, setOpenIndex] = useState<number | null>(null)

    return (
        <>
            <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{ __html: JSON.stringify(faqStructuredData) }}
            />

            <section className="max-w-3xl mx-auto px-6 py-24 border-t border-white/10">
                <div className="text-center mb-12">
                    {/* Section Label */}
                    <div className="text-[13px] text-[#5e6ad2] uppercase tracking-[0.15em] font-medium mb-4">
                        FAQ
                    </div>
                    <h2 className="text-[clamp(2rem,3.5vw,2.5rem)] font-[500] tracking-[-0.04em] text-white/95 mb-4">
                        Frequently Asked Questions
                    </h2>
                    <p className="text-[16px] text-white/[0.30]">
                        Everything you need to know about our AI content generator.
                    </p>
                </div>

                <div className="space-y-4">
                    {faqs.map((faq, index) => (
                        <div
                            key={index}
                            className="border border-white/10 rounded-xl bg-white/[0.02] overflow-hidden transition-all duration-300"
                        >
                            <button
                                className="w-full flex items-center justify-between p-6 text-left"
                                onClick={() => setOpenIndex(openIndex === index ? null : index)}
                            >
                                <span className="text-[15px] font-medium text-white/90 pr-8">{faq.question}</span>
                                <ChevronDown
                                    className={`w-5 h-5 text-white/40 transition-transform duration-300 ${openIndex === index ? 'rotate-180' : ''}`}
                                />
                            </button>
                            <div
                                className={`px-6 overflow-hidden transition-all duration-300 ease-in-out ${openIndex === index ? 'max-h-48 pb-6 opacity-100' : 'max-h-0 opacity-0'
                                    }`}
                            >
                                <p className="text-[14px] leading-relaxed text-white/50">
                                    {faq.answer}
                                </p>
                            </div>
                        </div>
                    ))}
                </div>
            </section>
        </>
    )
}
